# Generated by Django 4.1.7 on 2023-03-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_pub_date_alter_test_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesmember',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.test'),
        ),
    ]
