# Generated by Django 4.1.7 on 2023-03-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_votesmember_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
    ]
