# Generated by Django 4.1.7 on 2023-04-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votesmember',
            name='choice',
        ),
    ]
